name: Auto deploying google-sheet-lucky-draw to gh-page

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-to-gh-page:
    name: Deploy to gh-page
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{secrets.access_token}}
      USERNAME: 511234
      EMAIL: lulutheflaneur@gmail.com
      PUBLISH_DIR: ./build
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Prepare deployment
        run: echo Auto deployment triggered by ${{ github.event_name }}. Ready to deploy latest commits to gh-page
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Create production build
        run: npm run build
      - name: Deploy
        run: |
          cd $PUBLISH_DIR
          git init
          git config --local user.name $USERNAME
          git config --local user.email $EMAIL
          git remote add origin https://$ACCESS_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy to Github pages"
          git push origin gh-pages -f

      - name: Notify user of deployment completion
        run: echo Commits successfully deployed to gh-page
