name: Auto deploying google-sheet-lucky-draw to gh-page

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-to-gh-page:
    name: Deploy to gh-page
    runs-on: ubuntu-latest
    env:
      PUBLISH_DIR: ./build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Prepare deployment
        run: echo Auto deployment triggered by ${{ github.event_name }}. Ready to deploy latest commits to gh-page
      - name: Checkout branch
        uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: actions/deploy-pages@v4