name: Auto deploying google-sheet-lucky-draw to gh-page

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-to-gh-page:
    name: Deploy to gh-page 
    runs-on: ubuntu-latest
    # env:
      # ACCESS_TOKEN: ${{secrets.access_token}}
      # PUBLISH_DIR: ./dist
    # strategy:
    #   matrix:
    #     node-version: [16.x]

    steps:
      - name: Prepare deployment
        run: echo Auto deployment triggered by ${{ github.event_name }}. Ready to deploy latest commits to gh-page
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: npm run build
      - name: Deploy
        uses: 511234/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
      
      - name: Notify user of deployment completion
        run: echo Commits successfully deployed to gh-page