name: Auto deploying google-sheet-lucky-draw to gh-page

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-to-gh-page:
    name: Deploy to gh-page
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{secrets.access_token}}
      USERNAME: 511234
      EMAIL: lulutheflaneur@gmail.com
      PUBLISH_DIR: ./build

    steps:
      - name: Prepare deployment
        run: echo Auto deployment triggered by ${{ github.event_name }}. Ready to deploy latest commits to gh-page
      - name: Checkout branch
        uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Create production build
        run: npm run build
      - name: Deploy
        run: |
          cd $PUBLISH_DIR
          git init
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git checkout gh-pages
          git add --all
          git commit -m "Auto deploy to Github pages"
          git push origin HEAD:gh-pages --force

      - name: Notify user of deployment completion
        run: echo Commits successfully deployed to gh-page
